# https://ihenrywu.medium.com/how-to-update-python-flask-code-to-aws-ec2-with-an-automated-process-set-up-a-continuous-1c01ab321b8c
name: Deploy to AWS EC2

on:
  push:
    branches:
      - TBD

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to AWS EC2
      run: |
        # Setting up SSH Key
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # SSH options to bypass host key checking
        SSH_OPTIONS="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa"

        # SSH into EC2 and set up the virtual environment and install dependencies
        ssh $SSH_OPTIONS ec2-user@${{ secrets.EC2_HOST }} "
          # login to script runner account
          sudo su - script-runner
          cd /home/script-runner/My_Website_2
          
          # Update
          git fetch
          git pull
          
          # Activate the virtual environment
          source /home/script-runner/my_website_venv/bin/activate
        
          # Install the required packages
          TMPDIR=/home/script-runner/pip-cache pip3 install --cache-dir=/home/script-runner/pip-cache -r /home/script-runner/My_Website_2/requirements.txt 
        
          sudo systemctl daemon-reload  
          sudo systemctl restart gunicorn
          sudo systemctl restart nginx
        "
        
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
