# https://ihenrywu.medium.com/how-to-update-python-flask-code-to-aws-ec2-with-an-automated-process-set-up-a-continuous-1c01ab321b8c
name: Deploy to AWS EC2

on:
  push:
    branches:
      - TBD

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to AWS EC2
      run: |
        # Setting up SSH Key
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa

        # SSH options to bypass host key checking
        SSH_OPTIONS="-o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa"

        # Rsync to transfer the project to EC2
        rsync -avz --exclude='.git/' --exclude='.DS_Store' --exclude='venv_winjob' --exclude='__pycache__' --exclude='.gitattributes' --exclude='.gitignore' --exclude='history templates' --exclude='history version' --exclude='.env' -e "ssh $SSH_OPTIONS" $GITHUB_WORKSPACE/ ec2-user@${{ secrets.EC2_HOST }}:/home/ec2-user/winjob/

        # SSH into EC2 and set up the virtual environment and install dependencies
        ssh $SSH_OPTIONS ec2-user@${{ secrets.EC2_HOST }} "
          # Remove the existing virtual environment (if necessary)
          # rm -rf /home/ec2-user/winjob/venv_winjob
          # Create a new virtual environment
          # python3 -m venv /home/ec2-user/winjob/venv_winjob
          # Activate the virtual environment
          source /home/ec2-user/winjob/venv_winjob/bin/activate
          # Install the required packages
          pip3 install -r /home/ec2-user/winjob/requirements.txt
          # Additional commands to restart your application (if necessary)
          sudo systemctl restart gunicorn
        "
        
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
